<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Celestial Bodies</title>
    <link rel="stylesheet" href="view_style.css">
</head>
<body>
    <div class="gif-background">
        
        <img src="images/celestial.gif" class="gif-background" alt="Background GIF">
    </div>
    <div class="content">
    <h1>Celestial Bodies</h1>
    <p>Celestial bodies play fundamental roles in the universe, contributing to its structure, dynamics, and diversity. They provide valuable insights into the laws of physics, the origins of the cosmos, and the potential for life beyond Earth.</p>
    <h2>1. Stars</h2>
    <ul>
        <li>Stars are massive, luminous spheres of plasma held together by gravity, primarily composed of hydrogen and helium.</li>
        <li>They emit light and heat generated by nuclear fusion reactions in their cores.</li>
        <li>Stars vary in size, temperature, brightness, and lifespan, playing a crucial role in shaping galaxies and the universe's structure and evolution.</li>
    </ul>

    <h2>2. Planets</h2>
    <ul>
        <li>Planets are large celestial bodies that orbit stars and do not produce their own light.</li>
        <li>They are typically composed of rock, gas, or a combination of both, varying in size, composition, atmosphere, and surface features.</li>
        <li>The eight planets in our solar system include Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.</li>
    </ul>

    <h2>3. Moons (Natural Satellites)</h2>
    <ul>
        <li>Moons are natural satellites that orbit planets, varying in size from small rocky bodies to large worlds with complex geology and atmospheres.</li>
        <li>They can have diverse features, including craters, mountains, valleys, and volcanic activity, with Earth's Moon being the most well-known example.</li>
    </ul>

    <h2>4. Asteroids</h2>
    <ul>
        <li>Asteroids are rocky objects that orbit the Sun, primarily located in the asteroid belt between Mars and Jupiter.</li>
        <li>They vary in size from small rocky fragments to large bodies several hundred kilometers in diameter, with some having irregular shapes and moons of their own.</li>
        <li>Asteroids are remnants from the early solar system's formation.</li>
    </ul>

    <h2>5. Comets</h2>
    <ul>
        <li>Comets are icy bodies that orbit the Sun in elongated orbits, consisting of a nucleus of ice, dust, and rocky particles surrounded by a glowing coma and often a tail.</li>
        <li>They originate from the outer regions of the solar system and become visible when they approach the Sun, causing their ices to vaporize and form a bright tail.</li>
    </ul>

    <h2>6. Galaxies</h2>
    <ul>
        <li>Galaxies are massive systems containing stars, stellar remnants, interstellar gas, dust, and dark matter bound together by gravity.</li>
        <li>They come in various shapes and sizes, including spiral, elliptical, and irregular galaxies, hosting billions to trillions of stars and influencing the structure and evolution of the cosmos.</li>
    </ul>
    <h2>Celestial Body Data</h2>
    <?php
    $servername = "localhost";
    $username = "root";
    $password = "zZ@3Wnd4";
    $database = "space_dbms";

    $conn = new mysqli($servername, $username, $password, $database);

    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    $sql = "SELECT * FROM celestial_bodies";
    $result = $conn->query($sql);

    if (!$result) {
        die("Error: " . $conn->error);
    }

    if ($result->num_rows > 0) {
        echo "<table>";
        
        echo "<tr>";
        $row = $result->fetch_assoc();
        foreach ($row as $key => $value) {
            echo "<th>$key</th>";
        }
        echo "</tr>";
        
        do {
            echo "<tr>";
            foreach ($row as $value) {
                echo "<td>$value</td>";
            }
            echo "</tr>";
        } while ($row = $result->fetch_assoc());
        
        echo "</table>";
    } else {
        echo "0 results";
    }

    $conn->close();
    ?>
</body>
</html>
